# Generated by Django 5.0.2 on 2024-02-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # 상품 데이터 추가
        migrations.RunSQL(
            """
            INSERT INTO app_product (name, price, description, created_at, updated_at)
            VALUES
                ('아메리카노', 3000, '에스프레소에 물을 타서 만든 커피', NOW(), NOW()),
                ('카페라떼', 3500, '에스프레소에 스팀밀크를 타서 만든 커피', NOW(), NOW()),
                ('바닐라라떼', 4000, '카페라떼에 바닐라 시럽을 넣은 커피', NOW(), NOW()),
                ('카페모카', 4500, '카페라떼에 초콜릿 시럽을 넣은 커피', NOW(), NOW()),
                ('카라멜마끼아또', 4500, '카페라떼에 카라멜 시럽을 넣은 커피', NOW(), NOW());
            """
        ),
    ]
