# Generated by Django 5.0.2 on 2024-03-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_add_product_and_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'permissions': [('can_update_stock', '재고 관리 권한')], 'verbose_name': '상품 옵션', 'verbose_name_plural': '상품 옵션'},
        ),
    ]
