# Generated by Django 5.0.1 on 2024-01-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("preview_content", models.TextField()),
                ("url", models.URLField()),
                ("image", models.ImageField(upload_to="articles_image")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "verbose_name": "기사",
                "verbose_name_plural": "기사",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CuisineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
            ],
            options={
                "verbose_name": "음식 종류",
                "verbose_name_plural": "음식 종류",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "키워드",
                "verbose_name_plural": "키워드",
            },
        ),
        migrations.CreateModel(
            name="SocialChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "소셜채널",
                "verbose_name_plural": "소셜채널",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그",
            },
        ),
        migrations.CreateModel(
            name="RestaurantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                (
                    "cuisine_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fdc.cuisinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "가게 카테고리",
                "verbose_name_plural": "가게 카테고리",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "area_name",
                    models.CharField(max_length=100, verbose_name="지역 이름"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                (
                    "phone",
                    models.CharField(
                        help_text="E.164 포맷", max_length=16, verbose_name="전화번호"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="이미지 URL"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="별점"
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(verbose_name="별점 개수")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="영업 시작 시간"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="영업 종료 시간"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="위도",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="경도",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("keywords", models.ManyToManyField(blank=True, to="fdc.keyword")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fdc.restaurantcategory",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="fdc.tag")),
            ],
            options={
                "verbose_name": "가게",
                "verbose_name_plural": "가게",
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_representative", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="restaurant_images")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fdc.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "가게 이미지",
                "verbose_name_plural": "가게 이미지",
            },
        ),
        migrations.CreateModel(
            name="RestaurantMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fdc.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "가게 메뉴",
                "verbose_name_plural": "가게 메뉴",
            },
        ),
        migrations.CreateModel(
            name="RestaurantStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fdc.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "가게통계",
                "verbose_name_plural": "가게통계",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fdc.restaurant"
                    ),
                ),
                (
                    "social_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fdc.socialchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰",
                "verbose_name_plural": "리뷰",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="review_images")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fdc.review"
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰이미지",
                "verbose_name_plural": "리뷰이미지",
            },
        ),
    ]
