# Generated by Django 5.0 on 2023-12-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, db_index=True)),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
            ],
            options={
                'verbose_name': '가게 카테고리',
                'verbose_name_plural': '가게 카테고리',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('phone', models.CharField(db_index=True, help_text='E.164 포맷', max_length=16, verbose_name='전화번호')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='영업 시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='영업 종료 시간')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='위도')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9, verbose_name='경도')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, max_digits=3, verbose_name='별점')),
                ('rating_count', models.PositiveIntegerField(verbose_name='별점 개수')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('keywords', models.ManyToManyField(blank=True, to='restaurant.keyword')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantcategory')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': '가게 통계',
                'verbose_name_plural': '가게 통계',
            },
        ),
    ]
