# Generated by Django 5.0.6 on 2024-05-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
