# Generated by Django 5.0.6 on 2024-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogpost_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='read_count',
            field=models.IntegerField(default=1, verbose_name='조회수'),
        ),
    ]
