name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # 또는 배포하고자 하는 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=latest
        IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Update Lambda Function
      run: |
        FUNCTION_NAME=my-lambda-function
        aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $IMAGE_URI --region $AWS_REGION

env:
  AWS_REGION: us-east-1  # AWS 리전 설정
  ECR_REPOSITORY: my-ecr-repo  # ECR 레포지토리 이름
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # AWS 계정 ID
